"use client";

import { useState, useEffect } from "react";
import Sidebar from "@/components/sidebar";
import InsightsPanel from "@/components/insights-panel";

const API_BASE = "http://localhost:8000/api";

export default function InsightsPage() {
  const [transactions, setTransactions] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchTransactions = async () => {
      try {
        const res = await fetch(`${API_BASE}/transactions`);
        if (res.ok) {
          const data = await res.json();
          setTransactions(data);
        }
      } catch (err) {
        setError("Failed to load transaction data");
      } finally {
        setLoading(false);
      }
    };
    fetchTransactions();
  }, []);

  return (
    <div className="flex min-h-screen bg-[#0f1117]">
      <Sidebar />

      <main className="ml-64 flex-1 p-8 min-h-screen">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <span className="text-2xl">🧠</span>
            <h1 className="text-[#eef2ff] text-2xl font-bold">AI Insights</h1>
          </div>
          <p className="text-[#64748b] text-sm ml-11">
            Personalized financial insights powered by intelligent analysis of your spending patterns.
          </p>
        </div>

        {error && (
          <div className="bg-[#7f1d1d]/40 border border-[#ef4444]/30 rounded-xl px-4 py-3 mb-6">
            <p className="text-[#ef4444] text-sm">{error}</p>
          </div>
        )}

        <div className="max-w-3xl">
          {/* AI Engine Badge */}
          <div className="bg-[#1a1d2e] border border-[#2a2f44] rounded-xl p-4 mb-6 flex items-center gap-4">
            <div className="w-10 h-10 rounded-xl bg-[#6366f1]/15 flex items-center justify-center text-lg flex-shrink-0">
              🤖
            </div>
            <div className="flex-1">
              <p className="text-[#eef2ff] text-sm font-semibold">Rule-Based Analysis Engine</p>
              <p className="text-[#64748b] text-xs mt-0.5">
                Currently using client-side rule-based insights. OpenAI integration is planned for v2.
              </p>
            </div>
            <span className="text-xs bg-[#78350f]/40 text-[#f59e0b] px-2.5 py-1 rounded-full font-medium">MVP</span>
          </div>

          {/* Insights */}
          {loading ? (
            <div className="space-y-4">
              {[1, 2, 3].map((i) => (
                <div key={i} className="bg-[#1a1d2e] border border-[#2a2f44] rounded-xl p-5 animate-pulse">
                  <div className="h-4 bg-[#252a3a] rounded w-48 mb-3"></div>
                  <div className="h-3 bg-[#252a3a] rounded w-full mb-2"></div>
                  <div className="h-3 bg-[#252a3a] rounded w-3/4"></div>
                </div>
              ))}
            </div>
          ) : (
            <InsightsPanel transactions={transactions} />
          )}

          {/* Footer info */}
          <div className="mt-8 p-4 bg-[#1a1d2e]/50 border border-[#2a2f44] rounded-xl">
            <p className="text-[#64748b] text-xs text-center">
              Insights are generated by analyzing your transaction history. Add more transactions for better accuracy.
              {/* Future: OpenAI integration */}
              {/* Set OPENAI_API_KEY in .env to unlock AI-powered insights */}
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
